<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ml_cat_edit_music extends Model
{
    protected $fillable = [
            'compl_editar', 
            'compl_area_de_titulo', 
            'compl_area_de_edicion', 
            'compl_area_de_contenidos', 

            'cuerpo_tipo_de_musica',
            'ph_cuerpo_tipo_de_musica',  
            'cuerpo_titulo_de_la_obra', 
            'ph_cuerpo_titulo_de_la_obra', 
            'cuerpo_titulo', 
            'ph_cuerpo_titulo', 
            'cuerpo_subtitulo',
            'ph_cuerpo_subtitulo', 
            'cuerpo_artista', 
            'ph_cuerpo_artista', 
            'cuerpo_otros_artistas', 
            'ph_cuerpo_otros_artistas', 
            
            'cuerpo_musica', 
            'ph_cuerpo_musica', 
            'cuerpo_titulo_original', 
            'ph_cuerpo_titulo_original', 
            'cuerpo_titulo_del_disco', 
            'ph_cuerpo_titulo_del_disco', 
            'cuerpo_compositor', 
            'ph_cuerpo_compositor', 
            'cuerpo_director', 
            'ph_cuerpo_director', 
            'cuerpo_orquesta',
            'ph_cuerpo_orquesta', 
            'cuerpo_solista', 
            'ph_cuerpo_solista', 
            'cuerpo_productor',
            'ph_cuerpo_productor', 
            'cuerpo_adquirido', 
            'ph_cuerpo_adquirido', 
            'cuerpo_adecuado_para',
            'ph_cuerpo_adecuado_para',
            'cuerpo_genero', 
            'ph_cuerpo_genero', 
            'cuerpo_siglas_compositor', 
            'ph_cuerpo_siglas_compositor', 
            'cuerpo_siglas_titulo', 
            'ph_cuerpo_siglas_titulo', 
            'cuerpo_cdu', 
            'ph_cuerpo_cdu', 
            'cuerpo_valoracion', 
            'ph_cuerpo_valoracion', 
            'cuerpo_estado', 
            'ph_cuerpo_estado', 
            'cuerpo_editado_en', 
            'ph_cuerpo_editado_en', 
            'cuerpo_sello_discografico', 
            'ph_cuerpo_sello_discografico', 
            'cuerpo_anio_de_publicacion', 
            'ph_cuerpo_anio_de_publicacion', 
            'cuerpo_fotografia',
            'ph_cuerpo_fotografia', 
            'cuerpo_volumenes', 
            'ph_cuerpo_volumenes', 
            'cuerpo_duracion', 
            'ph_cuerpo_duracion',
            'cuerpo_formato', 
            'ph_cuerpo_formato', 
            'cuerpo_coleccion', 
            'ph_cuerpo_coleccion', 
            'cuerpo_ubicacion', 
            'ph_cuerpo_ubicacion', 
            'cuerpo_observacion',
            'ph_cuerpo_observacion', 
            'cuerpo_notas', 
            'ph_cuerpo_notas', 
            'cuerpo_idioma', 
            'ph_cuerpo_idioma', 
            'cuerpo_referencia', 
            'ph_cuerpo_referencia', 
            'cuerpo_imagen', 
            'ph_cuerpo_imagen', 
            'cuerpo_sinopsis', 
            'ph_cuerpo_sinopsis', 
    ];

    }
