<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ml_cat_edit_movie extends Model
{
    protected $fillable = [
            'cuerpo_desidherata', 
            'compl_area_de_titulo', 
            'compl_area_de_edicion', 
            'compl_area_de_contenidos',
            'compl_btn_cancelar',
            'compl_btn_guardar', 
  
            'cuerpo_titulo', 
            'ph_cuerpo_titulo',  
            'cuerpo_subtitulo',
            'ph_cuerpo_subtitulo',
            'cuerpo_director', 
            'ph_cuerpo_director',
            'cuerpo_reparto', 
            'ph_cuerpo_reparto',
            'cuerpo_titulo_original', 
            'ph_cuerpo_titulo_original',
            'cuerpo_adaptacion', 
            'ph_cuerpo_adaptacion', 
            'cuerpo_guion', 
            'ph_cuerpo_guion',
            'cuerpo_contenido_especifico', 
            'ph_cuerpo_contenido_especifico', 
            'cuerpo_adquirido', 
            'ph_cuerpo_adquirido',
            'cuerpo_adecuado_para',
            'ph_cuerpo_adecuado_para',
            'cuerpo_genero', 
            'ph_cuerpo_genero',
            'cuerpo_siglas_director', 
            'ph_cuerpo_siglas_director',
            'cuerpo_siglas_titulo', 
            'ph_cuerpo_siglas_titulo',
            'cuerpo_cdu', 
            'ph_cuerpo_cdu',
            'cuerpo_valoracion', 
            'ph_cuerpo_valoracion', 
            'cuerpo_estado', 
            'ph_cuerpo_estado',  
            'cuerpo_nacionalidad', 
            'ph_cuerpo_nacionalidad',
            'cuerpo_productora',
            'ph_cuerpo_productora', 
            'cuerpo_anio_de_publicacion', 
            'ph_cuerpo_anio_de_publicacion',
            'cuerpo_fotografia',
            'ph_cuerpo_fotografia', 
            'cuerpo_duracion', 
            'ph_cuerpo_duracion', 
            'cuerpo_formato', 
            'ph_cuerpo_formato',
            'cuerpo_distribuidora',
            'ph_cuerpo_distribuidora',
            'cuerpo_ubicacion', 
            'ph_cuerpo_ubicacion',
            'cuerpo_premios', 
            'ph_cuerpo_premios', 
            'cuerpo_notas', 
            'ph_cuerpo_notas',
            'cuerpo_idioma', 
            'ph_cuerpo_idioma',
            'cuerpo_referencia', 
            'ph_cuerpo_referencia',
            'cuerpo_imagen', 
            'ph_cuerpo_imagen',
            
            'cuerpo_sinopsis', 
            'ph_cuerpo_sinopsis',
        ]; 
}
